### ISSUE TITLE
Add `map` like functionality to read guards

### ISSUE THREAD

**Issue by whitfin** [smol-rs/async-lock#11]
One feature that the sync features of Tokio have is the ability to `map` guards such as `RwLockReadGuard`, which makes it possible to (e.g.) return a reference to a value inside a `RwLock<HashMap<T>>`. Is it possible that something such as this is added to this library?

Tokio docs for this API: https://docs.rs/tokio/1.1.0/tokio/sync/struct.RwLockReadGuard.html#method.map

**Comment by taiki-e** [comment]
I'm okay with adding this, but there are some safety issues to keep in mind when implementing/reviewing.

Actually, some of the major (Mutex|RwLock)::map implementations were unsound. https://github.com/tokio-rs/tokio/issues/3344, https://github.com/rust-lang/futures-rs/issues/2239, https://github.com/Amanieu/parking_lot/issues/259, https://github.com/Amanieu/parking_lot/issues/258

**Comment by notgull** [comment]
I think the costs outweigh the benefits in this case, especially given the impossibility of implementing this behavior soundly. Especially since well-written code shouldn't have to use mapped guards.

**Comment by touilleMan** [comment]
@notgull  sorry for commenting on a closed issue but I'm puzzled by your statement:

> Especially since well-written code shouldn't have to use mapped guards

td;dr: what do you think is the proper way to avoid avoid using mapped guard when a mutex wraps a structure where a cooking operation should be done when the lock is taken before returning the result to a caller (with lock still held) ?

My use case:

I find often useful to wrap low-level components (such as database connection) into a higher level structures in order to expose only business related methods:

```rust
let storage = Storage::start().await;

let mut transaction = storage.start_transaction().await;
transaction.change_balance("alice", 10).await;
transaction.change_balance("bob", -10).await;
transaction.commit().await;

// ...

struct Storage {
  db: AsyncMutex<SqliteConnection>
}
impl Storage {
  pub async fn open() -> Self { ... }
  pub async fn start_transaction(&'a self) -> StorageTransaction<'a> {
    let guard = db.lock().await;
    guard.execute("BEGIN TRANSACTION").await;
    StorageTransaction {
      guard
    }
  }
}

struct StorageTransaction<'a> {
  guard: AsyncMutexGuard<'a>
}
impl<'a> StorageTransaction {
  pub async fn change_balance(&'a self, user: &str, amount: isize) -> StorageTransaction<'a> {
    self.guard.execute("INSERT INTO balances(amount) VALUES (amount + ?) WHERE user = ?", amount, user).await
  }
  pub async fn commit(&self) {
    self.guard.execute("COMMIT").await;
  }
}
```

So far so good, however this falls apart if I replace `AsyncMutex<SqliteConnection>` by a `AsyncMutex<Option<SqliteConnection>>` (i.e. the database connection gets closed, typically by a `Storage::close(&self)` method).

In this case it seems logical to check if the connection is still open once in the `start_transaction` method, then have all the other `change_balance`/`commit` methods work on `SqliteConnection` (instead of having a `Option<SqliteConnection>` with the implicit guaranteed it has been checked for `None` in a previous step).

**Comment by notgull** [comment]
> td;dr: what do you think is the proper way to avoid avoid using mapped guard when a mutex wraps a structure where a cooking operation should be done when the lock is taken before returning the result to a caller (with lock still held) ?

I understand that in the short term mapped mutexes can seem like a solution to a problem, but overall there are much better solutions to this problem! There are two cases:

The first case is where the "operation" in question is a trivial operation, like unwrapping an `Option`.  At this point I'd recommend just `unwrap()`ing the guard when you need to perform some operation.

```rust
impl<'a> StorageTransaction {
  fn guard(&self) -> &SqliteConnection {
    self.guard.as_ref().unwrap()
  }
  pub async fn change_balance(&'a self, user: &str, amount: isize) -> StorageTransaction<'a> {
    self.guard().execute("INSERT INTO balances(amount) VALUES (amount + ?) WHERE user = ?", amount, user).await
  }
  pub async fn commit(&self) {
    self.guard().execute("COMMIT").await;
  }
}
```

At this point due to panic-branch prediction the compiler will likely optimize out most cases of the match here. If this isn't happening or if you want to be sure that it's optimized, `unwrap_unchecked()` can be used as well:

```rust
impl<'a> StorageTransaction {
  fn guard(&self) -> &SqliteConnection {
    // SAFETY: We know `guard` is `Some`
    unsafe { self.guard.as_ref().unwrap_unchecked() }
  }
}
```

This involves unsafe code, but mapped guards are also not implemented soundly (see https://github.com/Kimundi/owning-ref-rs/issues/49 and https://github.com/Storyyeller/stable_deref_trait/issues/10, despite the fact that the latter is closed it's still a fundamental issue). So pick your poison, I suppose.

The second is where it's actually a cold operation that can't reasonably be called multiple times. In this case you have to restructure your program. Make the lock, call the cold operation once, and then pass that to your functions. Like so:

```rust
async fn main() {
    let my_conn = /* ... */;
    let mut locked_conn = my_conn.lock().await;
    let mut mapped_thing = cold_operation(&mut locked_conn).await; // If it takes a while it should probably be implemented async-ly.
    
    change_balance(&mut mapped_thing).await;
    execute(&mut mapped_thing).await;
}
```

Unfortunately it's a flaw with Rust as a whole that it's difficult to pass around temporaries like this. However it's the only solution that doesn't open up soundness holes.

**Comment by touilleMan** [comment]
@notgull Thanks a lot for this detailed answer :smiley: 

As I understand, lock-map is a useful tool but cursed by Rust memory model.
![image](https://github.com/smol-rs/async-lock/assets/3187637/ea55b419-6924-48ba-ac8e-875511ef76d5)

After digging a bit into the link you provided, I stumbled on https://github.com/rust-lang/rfcs/pull/3467
As I understand, once this RFC is implemented it would be possible to have sound lock-map \o/

**Comment by coriolinus** [comment]
I keep coming back to this because the functionality would be really handy. But it's also not obvious how to best implement it. So here is the recipe!

```rust
/// An example of a thing we might implement. It's important for Reasons that we have interior mutability here.
pub struct Database {
    connection: Mutex<Option<DatabaseConnection>>,
}

#[derive(Debug, thiserror::Error)]
#[error("database has been closed")]
pub struct Closed;

// we don't want to need to do `db.connection.lock().await.ok_or(Closed)?` everywhere. 
// we also don't want to expose the mutex outside the module. So we introduce a helper

pub struct ConnectionGuard<'a> {
    guard: MutexGuard<'a, Option<DatabaseConnection>>,
}

impl<'a> TryFrom<MutexGuard<'a, Option<DatabaseConnection>>> for ConnectionGuard<'a> {
    type Error = Closed;

    fn try_from(guard: MutexGuard<'a, Option<DatabaseConnection>>) -> Result<Self, Self::Error> {
        guard
            .is_some()
            .then_some(Self {guard})
            .ok_or(Closed)
    }
}

impl Deref for ConnectionGuard<'_> {
    type Target = DatabaseConnection;

    fn deref(&self) -> &Self::Target {
        self.guard.as_ref().expect("we have exclusive access and already checked the connection exists")
    }
}

impl DerefMut for ConnectionGuard<'_> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.guard.as_mut().expect("we have exclusive access and already checked the connection exists")
    }
}

// only these impls ever touch `self.connection` directly
impl Database {
    pub async fn conn(&self) -> Result<ConnectionGuard<'_>, Closed> {
        self.connection.lock().await.try_into()
    }

    pub async fn close(&self) -> Result<DatabaseConnection, Closed> {
        let mut guard = self.connection.lock().await;
        guard.take().ok_or(Closed)
    }
}
```
